import Dexie from 'dexie'
import * as api_gw2 from "../../actions/gw2data"

const db = new Dexie('gw2database')
db.version(1).stores({
  tab_skill_list: '++id,&skill_id',
  tab_skill_info: '&skill_id,skill_info'
})
var need_to_update = true
updateSkillApi()

function updateSkillApi() {
  let skills = []
  api_gw2.getSkills().then((response) => {
    response.data.forEach((sid) => {
      skills.push({ skill_id: sid })
    })
    checkUpdate(skills.length).then(isUpdate => {
      if (isUpdate == true) {
        db.tab_skill_list.bulkPut(skills)

        filter_null_skill(response.data).then(skills_nodata => {
          getSkillsInfoGourp(skills_nodata)
        })
      } else {
        console.log("不用更新, need_to_update is", need_to_update)
      }
    })
    need_to_update = false
  })
}

function getSkillsInfoGourp(ids) {
  var str_id = ids.slice(0, 200).join(",")
  getSkillsInfo(str_id)
  if (ids.length > 200) {
    getSkillsInfoGourp(ids.slice(200))
  }
}

function getSkillsInfo(ids) {
  if (ids.length > 0) {
    api_gw2.getSkillsByIds(ids).then(response => {
      response.data.forEach(skill => {
        db.tab_skill_info.put({ skill_id: skill.id, skill_info: skill })
      })
    })
  }
}

async function filter_null_skill(ids) {
  let result = await db.tab_skill_info.toArray().then(items => {
    return ids.filter(id => !new Set(items.map(item => { return item.skill_id })).has(id))
  })
  return result
}

async function checkUpdate(ids_count) {
  if (need_to_update == true) {
    return true
  }
  if (ids_count != await db.tab_skill_list.count()) {
    return true
  }
  if (ids_count != await db.tab_skill_info.count()) {
    return true
  }
  console.log('最新技能列表', ids_count, '当前技能列表', await db.tab_skill_list.count(), '当前数据库技能', await db.tab_skill_info.count())
  return false
}

function updated() {
  need_to_update = true
}

export function getSkillsByProfession(profession) {
  return api_gw2.getProfessions(profession)
}

export async function getFlipskillByIds(ids) {
  let res_skills = await api_gw2.getSkillsByIds(ids);
  var skills = res_skills.data;
  for (let i in skills) {
    if (skills[i].flip_skill || skills[i].next_chain) {
      let res_flip = await getFlipskillByIds(skills[i].flip_skill + "," + skills[i].next_chain);
      skills = skills.concat(res_flip);
    }
  }
  return skills;
}

export function encodeChatLink(type, id) {
  var linkTypes = { item: 2, text: 3, map: 4, skill: 6, trait: 7, recipe: 9, skin: 10, outfit: 11 };
  if (!type) {
    return 'invalid type';
  }
  type = linkTypes[type.trim().toLowerCase()] || 0;
  if (!type) {
    return 'invalid type';
  }

  var data = [];
  while (id > 0) {
    data.push(id & 255);
    id = id >> 8;
  }
  while (data.length < 4 || data.length % 2 != 0) {
    data.push(0);
  }

  if (type == 2) {
    data.unshift(1);
  }
  data.unshift(type);

  // encode data
  var binary = '';
  for (var i = 0; i < data.length; i++) {
    binary += String.fromCharCode(data[i]);
  }
  return '[&' + btoa(binary) + ']';
}

export const PROFESSION = [
  {
    value: 'Guardian',
    label: '守护者'
  },
  {
    value: 'Warrior',
    label: '战士'
  },
  {
    value: 'Engineer',
    label: '工程师'
  },
  {
    value: 'Ranger',
    label: '游侠'
  },
  {
    value: 'Thief',
    label: '潜行者'
  },
  {
    value: 'Elementalist',
    label: '元素使'
  },
  {
    value: 'Mesmer',
    label: '幻术师'
  },
  {
    value: 'Necromancer',
    label: '唤灵师'
  },
  {
    value: 'Revenant',
    label: '魂武者'
  }
]

export const WEAPON = {
  Axe: "斧",
  Focus: "聚能器",
  Greatsword: "大剑",
  Spear: "矛",
  Pistol: "手枪",
  Scepter: "权杖",
  Shield: "盾",
  Staff: "法杖",
  Sword: "单手剑",
  Torch: "火炬",
  Trident: "三叉戟",
  Dagger: "匕首",
  Hammer: "巨锤",
  Longbow: "长弓",
  Mace: "钉锤",
  Rifle: "步枪",
  Speargun: "鱼叉枪",
  Warhorn: "号角",
  Shortbow: "短弓"
}

export const ATTRIBUTE = [
  {
    value: 'Power',
    label: '威力',
  },
  {
    value: 'Toughness',
    label: '坚韧',
  },
  {
    value: 'Vitality',
    label: '体力',
  },
  {
    value: 'Precision',
    label: '精准',
  },
  {
    value: 'CritDamage',
    label: '暴击效果',
  },
  {
    value: 'ConditionDamage',
    label: '症状伤害',
  },
  {
    value: 'Healing',
    label: '治疗效果',
  },
  {
    value: 'ConditionDuration',
    label: '症状效果',
  },
  {
    value: 'BoonDuration',
    label: '增益效果',
  }
]

export const EQUIPMENTTYPE = {
  Onehanded: "武器",
  Chest: "胸部",
  Legs: "腿部",
  Head: "头部",
  Shoulders: "肩部",
  Gloves: "手部",
  Boots: "足部",
  Amulet: "项链",
  Ring: "戒指",
  Accessory: "饰品",
  Backitem: "背部"
}


export const Gw2ProfessionMechanic =
  [
    { id: 41780, profession: "Guardian", name: "Tome of Resolve", chat_link: "[&BjSjAAA=]", description: "Virtue:  Regenerate health.Activate:  Draw forth an enchanted tome that recounts the trials undergone by the people of Vabbi.Each tome skill use consumes a page.", icon: "https://wiki.guildwars2.com/images/a/a9/Tome_of_Resolve.png", slot: "F2", bundle: "Profession mechanic", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "50" }, { icon: "https://wiki.guildwars2.com/images/a/a9/Tome_of_Resolve.png", text: "  Tome of Resolve: 84 (0.06)? Heal", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/9/9d/Maximum_Count.png", text: "  Pages: 5", type: "NoData" }] },
    { id: 44364, profession: "Guardian", name: "Tome of Justice", chat_link: "[&BkytAAA=]", description: "Virtue:  Burn foes every few attacks.Activate:  Pull forth a magical tome on the dangers of the blazing heat in Kourna.Each tome skill use consumes a page.", icon: "https://wiki.guildwars2.com/images/a/ae/Tome_of_Justice.png", slot: "F1", bundle: "Profession mechanic", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "30" }, { icon: "https://wiki.guildwars2.com/images/4/45/Burning.png", text: "  Burning (Passive) (2s): 262 Damage", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/9/9d/Maximum_Count.png", text: "  Pages: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Attacks to Trigger Passive: 5", type: "NoData" }] },
    { id: 44386, profession: "Engineer", name: "Holoforge Overheated", chat_link: "[&BmKtAAA=]", description: "Unable to reactivate until cooled.", icon: "https://wiki.guildwars2.com/images/4/4b/Overheat.png", slot: "", bundle: "Profession mechanic", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "0" }] },
    { id: 40988, profession: "Guardian", name: "Chapter 4: Stalwart Stand", chat_link: "[&BhygAAA=]", description: "Tome. Recount the stand of Elonian loyalists against Palawa Joko, granting resistance to your allies.", icon: "https://wiki.guildwars2.com/images/8/89/Chapter_4-_Stalwart_Stand.png", slot: "4", bundle: "Tome of Courage", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "10" }, { icon: "https://wiki.guildwars2.com/images/4/4b/Resistance.png", text: " 4 Resistance (1s): Nondamaging conditions currently on you are ineffective.", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Pulses: 4", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Pulses: 3", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/29/Interval.png", text: "  Interval: 1 second", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 360", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/1/1a/Combo.png", text: "  Combo Field: Light", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/7/7a/Breaks_stun.png", text: "  Breaks Stun", type: "NoData" }] },
    { id: 40015, profession: "Guardian", name: "Chapter 4: Scorched Aftermath", chat_link: "[&Bk+cAAA=]", description: "Tome. Detail the suffering in fire and blood inflicted during Vabbi's occupation.", icon: "https://wiki.guildwars2.com/images/c/c9/Chapter_4-_Scorched_Aftermath.png", slot: "4", bundle: "Tome of Justice", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "10" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage (5x): 1,135 (3.2)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage (5x): 710 (2.0)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/3/33/Bleeding.png", text: "  Bleeding (2s): 44 Damage", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/4/45/Burning.png", text: "  Burning (2s): 262 Damage", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Pulses: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/8/8b/Duration.png", text: "  Duration: 4 seconds", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/29/Interval.png", text: "  Interval: 1 second", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 360", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/1/1a/Combo.png", text: "  Combo Field: Fire", type: "NoData" }] },
    { id: 41836, profession: "Guardian", name: "Chapter 3: Valiant Bulwark", chat_link: "[&BmyjAAA=]", description: "Tome. Manifest the shimmering purity of the desert sun, reflecting enemy missiles.", icon: "https://wiki.guildwars2.com/images/7/73/Chapter_3-_Valiant_Bulwark.png", slot: "3", bundle: "Tome of Courage", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "8" }, { icon: "https://wiki.guildwars2.com/images/8/8b/Duration.png", text: "  Duration: 5 seconds", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 240", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Reflect Missiles", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 900", type: "NoData" }] },
    { id: 62885, profession: "Warrior", name: "Break Step", chat_link: "[&BqX1AAA=]", description: "Lunge forward with explosive force, damaging enemies at your starting position.", icon: "https://wiki.guildwars2.com/images/7/76/Break_Step.png", slot: "5", bundle: "Unsheathe Gunsaber", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "1" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 178 (0.5)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/4/46/Fury.png", text: "  Fury (5s): +25% Critical Chance", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/4/46/Fury.png", text: "  Fury (5s): +20% Critical Chance", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 3", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/9/9d/Maximum_Count.png", text: "  Maximum Count: 2", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f7/Count_Recharge.png", text: "  Count Recharge: 20 seconds", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 180", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/0/09/Explosion.png", text: "  Explosion", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/1/1a/Combo.png", text: "  Combo Finisher: Leap", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 450", type: "NoData" }] },
    { id: 44455, profession: "Guardian", name: "Epilogue: Unbroken Lines", chat_link: "[&BqetAAA=]", description: "Tome. Recalling the memory of heroes past, enchant nearby allies with formidable defenses.", icon: "https://wiki.guildwars2.com/images/d/d8/Epilogue-_Unbroken_Lines.png", slot: "5", bundle: "Tome of Courage", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "12" }, { icon: "https://wiki.guildwars2.com/images/e/e5/Aegis.png", text: "  Aegis (4s): Block the next incoming attack.", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6c/Protection.png", text: "  Protection (5s): -33% Incoming Damage", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/d/d8/Epilogue-_Unbroken_Lines.png", text: "  Unbroken Lines (5s): 300 Toughness", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/d/d8/Epilogue-_Unbroken_Lines.png", text: "  Unbroken Lines (5s): 200 Toughness", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/ae/Stability.png", text: "  Stability (5s): Cannot be knocked down, pushed back, pulled, launched, stunned, dazed, floated, sunk, feared, or taunted.", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 600", type: "NoData" }] },
    { id: 45128, profession: "Guardian", name: "Chapter 3: Azure Sun", chat_link: "[&BkiwAAA=]", description: "Tome. Inspired by countless poems describing the comforting powers of the water-reflected sun, grant boons to allies.", icon: "https://wiki.guildwars2.com/images/b/bf/Chapter_3-_Azure_Sun.png", slot: "3", bundle: "Tome of Resolve", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "8" }, { icon: "https://wiki.guildwars2.com/images/f/f4/Vigor.png", text: "  Vigor (5s): +50% Endurance Regeneration", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Regeneration.png", text: "  Regen (6s): 780 Heal", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/af/Swiftness.png", text: "  Swiftness (5s): +33% Movement Speed", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Allied Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 240", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 900", type: "NoData" }] },
    { id: 62789, profession: "Warrior", name: "Cyclone Trigger", chat_link: "[&BkX1AAA=]", description: "Spin and block enemy projectiles. Strikes all foes in melee range, then fires shots at foes out of melee range.", icon: "https://wiki.guildwars2.com/images/6/6c/Cyclone_Trigger.png", slot: "4", bundle: "Unsheathe Gunsaber", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "1" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 533 (1.5)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 444 (1.25)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Ranged Damage: 355 (1.0)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Blocks Missiles", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/8/8b/Duration.png", text: "  Missile Block Duration: 10.5½ seconds", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/9/9d/Maximum_Count.png", text: "  Maximum Count: 2", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f7/Count_Recharge.png", text: "  Count Recharge: 20 seconds", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 600", type: "NoData" }] },
    { id: 62930, profession: "Warrior", name: "Blooming Fire", chat_link: "[&BtL1AAA=]", description: "Slash with your blade and release a volley of explosions.", icon: "https://wiki.guildwars2.com/images/d/d0/Blooming_Fire.png", slot: "2", bundle: "Unsheathe Gunsaber", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "2" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 284 (0.8)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Explosion Damage (3x): 426 (1.2)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Explosion Damage (3x): 213 (0.6)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 3", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/9/9d/Maximum_Count.png", text: "  Maximum Count: 2", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f7/Count_Recharge.png", text: "  Count Recharge: 10 seconds", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/0/09/Explosion.png", text: "  Explosion", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 130", type: "NoData" }] },
    { id: 62772, profession: "Warrior", name: "Steel Divide", chat_link: "[&BjT1AAA=]", description: "Chain. Strike your foe again.", icon: "https://wiki.guildwars2.com/images/9/9a/Steel_Divide.png", slot: "1", bundle: "Unsheathe Gunsaber", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "0" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 337 (0.95)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 234 (0.66)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 3", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 130", type: "NoData" }] },
    { id: 63155, profession: "Thief", name: "Enter Shadow Shroud", chat_link: "[&BrP2AAA=]", description: "Ally target: Enter shadow shroud and tether a targeted or previously siphoned ally, granting them barrier. If no target is selected, one will be chosen randomly in the indicated radius.", icon: "https://wiki.guildwars2.com/images/f/f3/Enter_Shadow_Shroud.png", slot: "F2", bundle: "Profession mechanic", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "8" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Shroud Degeneration Rate: 2%", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Shroud Degeneration Rate: 4%", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/cc/Barrier.png", text: "  Barrier: 1,428 (0.5)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Total Shadow Shroud Health at Maximum Energy: 150%", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Maximum Stacks: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 1,200", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 1,200", type: "NoData" }] },
    { id: 62980, profession: "Warrior", name: "Dragon Slash—Boost", chat_link: "[&BgT2AAA=]", description: "Burst. Dash forward while slashing all foes in a line, ending Dragon Trigger. This attack consumes all charges to deal more damage.", icon: "https://wiki.guildwars2.com/images/7/75/Dragon_Slash%E2%80%94Boost.png", slot: "2", bundle: "Dragon Trigger", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "1" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Minimum Damage: 327 (0.92)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Minimum Damage: 152 (0.429)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Maximum Damage: 5,790 (16.3)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Maximum Damage: 368 (1.037)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/0/09/Explosion.png", text: "  Explosion", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 750", type: "NoData" }] },
    { id: 63365, profession: "Engineer", name: "Explosive Knuckle", chat_link: "[&BoX3AAA=]", description: "Mech Command. Order your mech to dash at a target, punching with an explosive strike that weakens enemies near the point of impact.", icon: "https://wiki.guildwars2.com/images/1/15/Explosive_Knuckle.png", slot: "F1", bundle: "Profession mechanic", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "15" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 2,992 (1.8)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 1,030 (0.62)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f9/Weakness.png", text: "  Weakness (5s): -50% Endurance Regeneration, +50% Fumble (Unrestricted)", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 240", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/0/09/Explosion.png", text: "  Explosion", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 600", type: "NoData" }] },
    { id: 63362, profession: "Thief", name: "Haunt Shot", chat_link: "[&BoL3AAA=]", description: "Shroud. Unleash darkness in a targeted area, inflicting conditions on foes and gaining might for each target struck. Heal your tethered ally and grant them might based on the number of targets struck.", icon: "https://wiki.guildwars2.com/images/b/be/Haunt_Shot.png", slot: "1", bundle: "Enter Shadow Shroud", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "0" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 441 (1.075)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 185 (0.45)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/0/08/Torment.png", text: "  Torment (5s): 110 Damage, 159 Damage if Foe Is Stationary", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/7/7c/Might.png", text: "  Might (5s): 30 Condition Damage, 30 Power", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f9/Attribute_bonus.png", text: "  Tethered Ally Healing per Target: 514 (0.1)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 3", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 180", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 900", type: "NoData" }] },
    { id: 63251, profession: "Thief", name: "Exit Shadow Shroud", chat_link: "[&BhP3AAA=]", description: "Exit your shadow shroud, breaking the tether between you and your ally.", icon: "https://wiki.guildwars2.com/images/b/bf/Exit_Shadow_Shroud.png", slot: "F2", bundle: "Profession mechanic", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "0" }] },
    { id: 63293, profession: "Engineer", name: "Crisis Zone", chat_link: "[&Bj33AAA=]", description: "Mech Command. Your mech removes conditions, breaks stuns, and grants boons to itself and nearby allies.The mech does not count against the target count for this skill.", icon: "https://wiki.guildwars2.com/images/0/09/Crisis_Zone.png", slot: "F2", bundle: "Profession mechanic", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "30" }, { icon: "https://wiki.guildwars2.com/images/e/e5/Aegis.png", text: "  Aegis (3s): Block the next incoming attack.", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/ae/Stability.png", text: "  Stability (15s): Cannot be knocked down, pushed back, pulled, launched, stunned, dazed, floated, sunk, feared, or taunted.", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/ae/Stability.png", text: "  Stability (8s): Cannot be knocked down, pushed back, pulled, launched, stunned, dazed, floated, sunk, feared, or taunted.", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6c/Protection.png", text: "  Protection (6s): -33% Incoming Damage", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6c/Protection.png", text: "  Protection (5s): -33% Incoming Damage", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/4/4c/Alacrity.png", text: "  Alacrity (6s): +25% Skill Recharge Rate", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/4/4c/Alacrity.png", text: "  Alacrity (5s): +25% Skill Recharge Rate", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Conditions Removed: 3", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 600", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/7/7a/Breaks_stun.png", text: "  Breaks Stun", type: "NoData" }] },
    { id: 63107, profession: "Thief", name: "Grasping Shadows (underwater)", chat_link: "[&BoP2AAA=]", description: "Shroud. Unleash darkness on your target's location, inflicting conditions on foes. Cleanse conditions from yourself while healing and cleansing your tethered ally, based on targets struck.", icon: "https://wiki.guildwars2.com/images/e/ef/Grasping_Shadows.png", slot: "2", bundle: "Enter Shadow Shroud", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "3" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 513 (1.25)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/fb/Crippled.png", text: "  Cripple (3s): -50% Movement Speed", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/0/08/Torment.png", text: " 2 Torment (10s): 440 Damage, 636 Damage if Foe Is Stationary", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Conditions Removed: 1", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f9/Attribute_bonus.png", text: "  Tethered Ally Healing per Target: 517 (0.1)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 180", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 900", type: "NoData" }] },
    { id: 63367, profession: "Engineer", name: "Discharge Array", chat_link: "[&Bof3AAA=]", description: "Mech Command. Cycle energy into your mech's armor to turn it into a lightning rod. Jade energy strikes nearby foes and inflicts conditions on them.", icon: "https://wiki.guildwars2.com/images/3/3c/Discharge_Array.png", slot: "F2", bundle: "Profession mechanic", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "30" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 499 (0.3)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 499 (0.3)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f5/Slow.png", text: "  Slow (2s): Skills and actions are slower.", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f5/Slow.png", text: "  Slow (1s): Skills and actions are slower.", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/e/e6/Confusion.png", text: " 2 Confusion (5s): 100 Damage, 99 Damage to Players on Skill Use, 191 Damage to Non-Players on Skill Use", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/e/e6/Confusion.png", text: " 2 Confusion (2s): 40 Damage, 99 Damage to Players on Skill Use, 191 Damage to Non-Players on Skill Use", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/4/45/Burning.png", text: "  Burning (3s): 393 Damage", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/4/45/Burning.png", text: "  Burning (2s): 262 Damage", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Number of Hits: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 3", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/29/Interval.png", text: "  Interval: 1 second", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 240", type: "NoData" }] },
    { id: 63121, profession: "Engineer", name: "Jade Mortar", chat_link: "[&BpH2AAA=]", description: "Mech Command. Launch a powerful mortar attack at the target.", icon: "https://wiki.guildwars2.com/images/a/af/Jade_Mortar.png", slot: "F3", bundle: "Profession mechanic", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "20" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 3,656 (2.2)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 1,994 (1.2)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/4/45/Burning.png", text: " 3 Burning (3s): 1,179 Damage", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/7/79/Daze.png", text: "  Daze: 1 second", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 240", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/0/09/Explosion.png", text: "  Explosion", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/e/e2/Evade.png", text: "  Defiance Break: 100", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 1,500", type: "NoData" }] },
    { id: 62797, profession: "Warrior", name: "Dragon Slash—Force", chat_link: "[&Bk31AAA=]", description: "Burst. Slash foes in front of you, ending Dragon Trigger. This attack consumes all charges to deal more damage.", icon: "https://wiki.guildwars2.com/images/b/b5/Dragon_Slash%E2%80%94Force.png", slot: "1", bundle: "Dragon Trigger", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "1" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Minimum Damage: 412 (1.16)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Minimum Damage: 190 (0.535)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Maximum Damage: 7,246 (20.4)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Maximum Damage: 460 (1.295)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/0/09/Explosion.png", text: "  Explosion", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 300", type: "NoData" }] },
    { id: 42925, profession: "Guardian", name: "Epilogue: Eternal Oasis", chat_link: "[&Bq2nAAA=]", description: "Tome. Purify your allies with the waters of Amnoon and increase the healing they receive.", icon: "https://wiki.guildwars2.com/images/5/5f/Epilogue-_Eternal_Oasis.png", slot: "5", bundle: "Tome of Resolve", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "12" }, { icon: "https://wiki.guildwars2.com/images/5/5f/Epilogue-_Eternal_Oasis.png", text: "  Eternal Oasis (8s): +33% Heal Effectiveness", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/5f/Epilogue-_Eternal_Oasis.png", text: "  Eternal Oasis (8s): +20% Heal Effectiveness", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Conditions Converted to Boons: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Conditions Converted to Boons: 2", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 600", type: "NoData" }] },
    { id: 63220, profession: "Thief", name: "Dawn's Repose", chat_link: "[&BvT2AAA=]", description: "Shroud. Leap to the targeted area, inflicting fear on foes at your ending point. Grant barrier to your tethered ally and yourself based on targets struck. Heal your tethered ally based on targets struck.", icon: "https://wiki.guildwars2.com/images/3/31/Dawn%27s_Repose.png", slot: "3", bundle: "Enter Shadow Shroud", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "8" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 410 (1.0)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 4 (0.01)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/cc/Barrier.png", text: "  Minimum Barrier: 1,605 (0.5)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/cc/Barrier.png", text: "  Maximum Barrier: 6,405 (0.5)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/e/e6/Fear.png", text: "  Fear (1s): Involuntary retreat; unable to act; stacks duration.", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f9/Attribute_bonus.png", text: "  Tethered Ally Healing per Target: 514 (0.1)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 180", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/1/1a/Combo.png", text: "  Combo Finisher: Leap", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 450", type: "NoData" }] },
    { id: 63141, profession: "Engineer", name: "Barrier Burst", chat_link: "[&BqX2AAA=]", description: "Mech Command. Pulse a barrier and boons to all nearby allies.The mech does not count against the target count for this skill.", icon: "https://wiki.guildwars2.com/images/8/8e/Barrier_Burst.png", slot: "F3", bundle: "Profession mechanic", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "30" }, { icon: "https://wiki.guildwars2.com/images/c/cc/Barrier.png", text: "  Barrier per Pulse: 434 (0.43)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/cc/Barrier.png", text: "  Barrier per Pulse: 260 (0.43)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/7/7c/Might.png", text: " 3 Might (15s): 90 Condition Damage, 90 Power", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/7/7c/Might.png", text: " 2 Might (8s): 60 Condition Damage, 60 Power", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/4/46/Fury.png", text: "  Fury (3s): +25% Critical Chance", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/4/46/Fury.png", text: "  Fury (10.5½s): +20% Critical Chance", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Pulses: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 360", type: "NoData" }] },
    { id: 41123, profession: "Engineer", name: "Deactivate Photon Forge", chat_link: "[&BqOgAAA=]", description: "Cancel Photon Forge and begin cooling after a delay. Cooling effectiveness increases over time.", icon: "https://wiki.guildwars2.com/images/4/45/Deactivate_Photon_Forge.png", slot: "F5", bundle: "Profession mechanic", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "6" }, { icon: "https://wiki.guildwars2.com/images/c/c4/Heat.png", text: "  Heat Lost per Second: 5%", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c4/Heat.png", text: "  Improved Heat Lost per Second: 10%", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/8/8b/Duration.png", text: "  Cooling Delay: 3 seconds", type: "NoData" }] },
    { id: 63167, profession: "Thief", name: "Grasping Shadows", chat_link: "[&Br/2AAA=]", description: "Shroud. Unleash darkness in a targeted area, inflicting conditions on foes. Cleanse conditions from yourself while healing and cleansing your tethered ally, based on targets struck.", icon: "https://wiki.guildwars2.com/images/e/ef/Grasping_Shadows.png", slot: "2", bundle: "Enter Shadow Shroud", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "3" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 684 (1.666)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/fb/Crippled.png", text: "  Cripple (3s): -50% Movement Speed", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/0/08/Torment.png", text: " 2 Torment (10s): 440 Damage, 636 Damage if Foe Is Stationary", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/0/08/Torment.png", text: " 2 Torment (5s): 220 Damage, 318 Damage if Foe Is Stationary", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Conditions Removed: 1", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f9/Attribute_bonus.png", text: "  Tethered Ally Healing per Target: 517 (0.1)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 180", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/1/1a/Combo.png", text: "  Combo Finisher: Blast", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 900", type: "NoData" }] },
    { id: 45890, profession: "Engineer", name: "Flash Cutter", chat_link: "[&BkKzAAA=]", description: "Cleave through all foes in front of you twice.", icon: "https://wiki.guildwars2.com/images/1/1c/Flash_Cutter.png", slot: "1", bundle: "Engage Photon Forge", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "0" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage (2x): 626 (1.6)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage (2x): 416 (1.066)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c4/Heat.png", text: "  Heat Gained: 2%", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 240", type: "NoData" }] },
    { id: 62732, profession: "Warrior", name: "Artillery Slash", chat_link: "[&Bgz1AAA=]", description: "Shoot a shell from your sword that explodes on the first enemy hit.", icon: "https://wiki.guildwars2.com/images/6/68/Artillery_Slash.png", slot: "3", bundle: "Unsheathe Gunsaber", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "0" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 409 (1.15)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/fb/Crippled.png", text: "  Cripple (2s): -50% Movement Speed", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 3", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/9/9d/Maximum_Count.png", text: "  Maximum Count: 3", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f7/Count_Recharge.png", text: "  Count Recharge: 15 seconds", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/0/09/Explosion.png", text: "  Explosion", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/1/1a/Combo.png", text: "  Combo Finisher: Physical Projectile", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 900", type: "NoData" }] },
    { id: 42449, profession: "Guardian", name: "Chapter 3: Heated Rebuke", chat_link: "[&BtGlAAA=]", description: "Tome. Call forth a heated vortex to collapse your enemies together.", icon: "https://wiki.guildwars2.com/images/e/e7/Chapter_3-_Heated_Rebuke.png", slot: "3", bundle: "Tome of Justice", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "8" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 160 (0.45)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 4 (0.01)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/3/31/Pull.png", text: "  Pull: 240", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 240", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/e/e2/Evade.png", text: "  Defiance Break: 150", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 900", type: "NoData" }] },
    { id: 45022, profession: "Guardian", name: "Chapter 1: Desert Bloom", chat_link: "[&Bt6vAAA=]", description: "Tome. Tales of desert blooms create a wave of healing for your allies.", icon: "https://wiki.guildwars2.com/images/f/fd/Chapter_1-_Desert_Bloom.png", slot: "1", bundle: "Tome of Resolve", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "0" }, { icon: "https://wiki.guildwars2.com/images/f/f3/Healing.png", text: "  Healing: 602 (1.1)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f3/Healing.png", text: "  Healing: 564 (0.3)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Allied Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 600", type: "NoData" }] },
    { id: 41258, profession: "Guardian", name: "Chapter 1: Searing Spell", chat_link: "[&BiqhAAA=]", description: "Tome. Fueled by tales of the desolation in Istan, incite a great swelling of heat before you.", icon: "https://wiki.guildwars2.com/images/d/d3/Chapter_1-_Searing_Spell.png", slot: "1", bundle: "Tome of Justice", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "0" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 337 (0.95)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 213 (0.6)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/4/45/Burning.png", text: "  Burning (20.5½s): 328 Damage", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 600", type: "NoData" }] },
    { id: 45783, profession: "Engineer", name: "Photon Blitz", chat_link: "[&BteyAAA=]", description: "Fire multiple piercing blasts at your target.", icon: "https://wiki.guildwars2.com/images/8/85/Photon_Blitz.png", slot: "4", bundle: "Engage Photon Forge", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "10" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage (8x): 2,000 (5.12)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage (8x): 624 (1.6)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c4/Heat.png", text: "  Heat Gained: 2%", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/4/45/Burning.png", text: " 8 Burning (1s): 1,048 Damage", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/ae/Pierces.png", text: "  Pierces", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/1/1a/Combo.png", text: "  Combo Finisher: Physical Projectile (20% chance)", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 600", type: "NoData" }] },
    { id: 42521, profession: "Engineer", name: "Holographic Shockwave", chat_link: "[&BhmmAAA=]", description: "Create a deadly holographic shockwave that launches foes upward. This attack always deals a critical hit.", icon: "https://wiki.guildwars2.com/images/b/b3/Holographic_Shockwave.png", slot: "5", bundle: "Engage Photon Forge", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "15" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 375 (0.96)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 4 (0.01)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c4/Heat.png", text: "  Heat Gained: 25%", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/d/dd/Precision_attribute.png", text: "  Critical Chance Increase: 100%", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/68/Launch.png", text: "  Launch: 0", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/1/1a/Combo.png", text: "  Combo Finisher: Blast", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/e/e2/Evade.png", text: "  Defiance Break: 232", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 300", type: "NoData" }] },
    { id: 44530, profession: "Engineer", name: "Corona Burst", chat_link: "[&BvKtAAA=]", description: "Strike nearby foes and begin to store up energy, gaining boons and heat each pulse. After charging, the energy explodes, inflicting conditions on nearby foes.", icon: "https://wiki.guildwars2.com/images/b/b3/Corona_Burst.png", slot: "3", bundle: "Engage Photon Forge", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "6" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 469 (1.2)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 375 (0.96)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c4/Heat.png", text: "  Heat Gained: 2%", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/7/7c/Might.png", text: " 2 Might (8s): 60 Condition Damage, 60 Power", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/7/7c/Might.png", text: "  Might (6s): 30 Condition Damage, 30 Power", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/af/Vulnerability.png", text: " 8 Vulnerability (8s): +8% Incoming Damage, +8% Incoming Condition Damage", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/af/Vulnerability.png", text: " 8 Vulnerability (6s): +8% Incoming Damage, +8% Incoming Condition Damage", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Number of Hits: 2", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Pulses: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 300", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/0/09/Explosion.png", text: "  Explosion", type: "NoData" }] },
    { id: 42965, profession: "Engineer", name: "Holo Leap", chat_link: "[&BtWnAAA=]", description: "Create a holographic launch pad and leap to your foe. The pad remains behind for a short duration, granting increased movement speed to allies who touch it.", icon: "https://wiki.guildwars2.com/images/3/3b/Holo_Leap.png", slot: "2", bundle: "Engage Photon Forge", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "2" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 704 (1.8)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 356 (0.91)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c4/Heat.png", text: "  Heat Gained: 7%", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/af/Swiftness.png", text: "  Swiftness (3s): +33% Movement Speed", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 3", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/8/8b/Duration.png", text: "  Duration: 3 seconds", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/1/1a/Combo.png", text: "  Combo Finisher: Leap", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 600", type: "NoData" }] },
    { id: 45219, profession: "Engineer", name: "Deactivate Photon Forge (hot)", chat_link: "[&BqOwAAA=]", description: "Cancel Photon Forge and begin cooling after a delay. Cooling effectiveness increases over time.", icon: "https://wiki.guildwars2.com/images/6/65/Deactivate_Photon_Forge_%28hot%29.png", slot: "F5", bundle: "Photon Projector", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "6" }, { icon: "https://wiki.guildwars2.com/images/c/c4/Heat.png", text: "  Heat Lost per Second: 5%", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c4/Heat.png", text: "  Improved Heat Lost per Second: 10%", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/8/8b/Duration.png", text: "  Cooling Delay: 3 seconds", type: "NoData" }] },
    { id: 42938, profession: "Engineer", name: "Engage Photon Forge", chat_link: "[&BrqnAAA=]", description: "Activate your Photon Forge, gaining access to new skills. Generate heat while Photon Forge is active. Take damage if you overheat. Disables use of kits for a short duration.", icon: "https://wiki.guildwars2.com/images/d/dd/Engage_Photon_Forge.png", slot: "F5", bundle: "Photon Projector", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "1" }, { icon: "https://wiki.guildwars2.com/images/c/c4/Heat.png", text: "  Heat per Second: 2%", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c4/Heat.png", text: "  Maximum Heat: 100", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/8/8b/Duration.png", text: "  Kit disable time: 6 seconds", type: "NoData" }] },
    { id: 62966, profession: "Warrior", name: "Swift Cut", chat_link: "[&Bvb1AAA=]", description: "Chain. Slash your foe.", icon: "https://wiki.guildwars2.com/images/e/e3/Swift_Cut.png", slot: "1", bundle: "Unsheathe Gunsaber", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "0" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 249 (0.7)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 174 (0.49)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 3", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 130", type: "NoData" }] },
    { id: 63188, profession: "Engineer", name: "Spark Revolver", chat_link: "[&BtT2AAA=]", description: "Mech Command. Fire a rapid volley of jade energy bolts from both arms, piercing through all enemies.", icon: "https://wiki.guildwars2.com/images/4/42/Spark_Revolver.png", slot: "F1", bundle: "Profession mechanic", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "20" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage (12x): 3,516 (2.112)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage (12x): 1,740 (1.05)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/ae/Pierces.png", text: "  Pierces", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 1,200", type: "NoData" }] },
    { id: 63345, profession: "Engineer", name: "Core Reactor Shot", chat_link: "[&BnH3AAA=]", description: "Mech Command. Charge up and then release a powerful ball of jade energy at your target that explodes on contact.", icon: "https://wiki.guildwars2.com/images/c/c9/Core_Reactor_Shot.png", slot: "F2", bundle: "Profession mechanic", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "25" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 4,155 (2.5)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 17 (0.01)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/68/Launch.png", text: "  Launch: 240", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 240", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/0/09/Explosion.png", text: "  Explosion", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/e/e2/Evade.png", text: "  Defiance Break: 232", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 1,200", type: "NoData" }] },
    { id: 62918, profession: "Warrior", name: "Explosive Thrust", chat_link: "[&Bsb1AAA=]", description: "Chain. Hit your foe with a final, brutal stab, and fire a shot that causes a secondary explosion.", icon: "https://wiki.guildwars2.com/images/9/99/Explosive_Thrust.png", slot: "1", bundle: "Unsheathe Gunsaber", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "0" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 355 (1.0)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 373 (1.05)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Secondary Explosions: 107 (0.3)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Secondary Explosions: 71 (0.2)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 3", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/0/09/Explosion.png", text: "  Explosion", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 130", type: "NoData" }] },
    { id: 42898, profession: "Guardian", name: "Epilogue: Ashes of the Just", chat_link: "[&BpKnAAA=]", description: "Tome. Recall the memory of fallen heroes, granting allies the searing blades of justice.", icon: "https://wiki.guildwars2.com/images/6/6d/Epilogue-_Ashes_of_the_Just.png", slot: "5", bundle: "Tome of Justice", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "12" }, { icon: "https://wiki.guildwars2.com/images/6/6d/Epilogue-_Ashes_of_the_Just.png", text: " 3 Ashes of the Just (10s): Your next strike burns with justice.", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/4/45/Burning.png", text: "  Burning (3s): 393 Damage", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Allied Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/29/Interval.png", text: "  Interval: 1 second", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 600", type: "NoData" }] },
    { id: 63227, profession: "Thief", name: "Dawn's Repose (underwater)", chat_link: "[&Bvv2AAA=]", description: "Shroud. Dash in the direction you are facing, applying fear to foes at your end point. Grant barrier to your tethered ally and yourself based on the targets struck. Heal your tethered ally based on targets struck.", icon: "https://wiki.guildwars2.com/images/3/31/Dawn%27s_Repose.png", slot: "3", bundle: "Enter Shadow Shroud", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "8" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 205 (0.5)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/cc/Barrier.png", text: "  Minimum Barrier: 1,605 (0.5)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/cc/Barrier.png", text: "  Maximum Barrier: 9,605 (0.5)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/e/e6/Fear.png", text: "  Fear (1s): Involuntary retreat; unable to act; stacks duration.", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f9/Attribute_bonus.png", text: "  Tethered Ally Healing per Target: 514 (0.1)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 600", type: "NoData" }] },
    { id: 44588, profession: "Engineer", name: "Light Strike", chat_link: "[&BiyuAAA=]", description: "Swing a holographic blade.", icon: "https://wiki.guildwars2.com/images/f/f7/Light_Strike.png", slot: "1", bundle: "Engage Photon Forge", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "0" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 391 (1.0)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 156 (0.4)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c4/Heat.png", text: "  Heat Gained: 2%", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 240", type: "NoData" }] },
    { id: 40635, profession: "Guardian", name: "Chapter 2: Igniting Burst", chat_link: "[&BrueAAA=]", description: "Tome. Ignite the air around you in an expanding burst.", icon: "https://wiki.guildwars2.com/images/5/53/Chapter_2-_Igniting_Burst.png", slot: "2", bundle: "Tome of Justice", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "4" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 195 (0.55)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/4/45/Burning.png", text: "  Burning (10s): 1,310 Damage", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/4/45/Burning.png", text: "  Burning (5s): 655 Damage", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f9/Weakness.png", text: "  Weakness (4s): -50% Endurance Regeneration, +50% Fumble (Unrestricted)", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f9/Weakness.png", text: "  Weakness (2s): -50% Endurance Regeneration, +50% Fumble (Unrestricted)", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 240", type: "NoData" }] },
    { id: 63236, profession: "Engineer", name: "Sky Circus", chat_link: "[&BgT3AAA=]", description: "Mech Command. Your mech jets into the air and fires a missile at each nearby foe before crashing down and dealing additional damage to anything caught underfoot.", icon: "https://wiki.guildwars2.com/images/8/8c/Sky_Circus.png", slot: "F3", bundle: "Profession mechanic", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "30" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Missile Damage: 997 (0.6)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Landing Damage: 1,994 (1.2)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Landing Damage: 17 (0.01)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/4/45/Burning.png", text: "  Burning (5s): 655 Damage", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/68/Launch.png", text: "  Knockback on Landing: 100", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Targets per Missile: 3", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 600", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Missile Explosion Radius: 120", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/e/e2/Evade.png", text: "  Evade: 10.25¼ seconds", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/e/e2/Evade.png", text: "  Defiance Break: 232", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 600", type: "NoData" }] },
    { id: 42986, profession: "Guardian", name: "Chapter 1: Unflinching Charge", chat_link: "[&BuqnAAA=]", description: "Tome. Roused by tales of mythical Sunspear charges, ground and motivate allies before you.", icon: "https://wiki.guildwars2.com/images/3/30/Chapter_1-_Unflinching_Charge.png", slot: "1", bundle: "Tome of Courage", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "0" }, { icon: "https://wiki.guildwars2.com/images/a/ae/Stability.png", text: "  Stability (4s): Cannot be knocked down, pushed back, pulled, launched, stunned, dazed, floated, sunk, feared, or taunted.", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/ae/Stability.png", text: "  Stability (1s): Cannot be knocked down, pushed back, pulled, launched, stunned, dazed, floated, sunk, feared, or taunted.", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/af/Swiftness.png", text: "  Swiftness (6s): +33% Movement Speed", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Allied Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 600", type: "NoData" }] },
    { id: 63334, profession: "Engineer", name: "Rolling Smash", chat_link: "[&Bmb3AAA=]", description: "Mech Command. Slam at the target with both cutters, inflicting severe bleeding to enemies in the area.", icon: "https://wiki.guildwars2.com/images/4/48/Rolling_Smash.png", slot: "F1", bundle: "Profession mechanic", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "20" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 2,659 (1.6)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 1,330 (0.8)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/3/33/Bleeding.png", text: " 8 Bleeding (8s): 1,408 Damage", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/3/33/Bleeding.png", text: " 4 Bleeding (8s): 704 Damage", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 180", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 600", type: "NoData" }] },
    { id: 41968, profession: "Guardian", name: "Chapter 2: Daring Challenge", chat_link: "[&BvCjAAA=]", description: "Tome. As the tales recount of Turai, taunt your enemies by issuing an insightfully inciting challenge.", icon: "https://wiki.guildwars2.com/images/7/79/Chapter_2-_Daring_Challenge.png", slot: "2", bundle: "Tome of Courage", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "4" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 497 (1.4)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 4 (0.01)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/cc/Taunt.png", text: "  Taunt (1s): Involuntarily attack foes.", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/0/06/Resolution.png", text: "  Resolution (3s): Incoming condition damage decreased by 33%.", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 240", type: "NoData" }] },
    { id: 45756, profession: "Engineer", name: "Bright Slash", chat_link: "[&BryyAAA=]", description: "Slash with a blade of light energy.", icon: "https://wiki.guildwars2.com/images/f/fa/Bright_Slash.png", slot: "1", bundle: "Engage Photon Forge", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "0" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 391 (1.0)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 260 (0.666)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c4/Heat.png", text: "  Heat Gained: 2%", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 240", type: "NoData" }] },
    { id: 63249, profession: "Thief", name: "Mind Shock", chat_link: "[&BhH3AAA=]", description: "Shroud. After a short channel, unleash a blast of compressed magic that stuns enemies. You and your tethered ally gain stability, with stability gaining bonus duration for each enemy struck. Heal your tethered ally based on each enemy you hit.", icon: "https://wiki.guildwars2.com/images/e/e6/Mind_Shock.png", slot: "5", bundle: "Enter Shadow Shroud", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "16" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 821 (2.0)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage: 4 (0.01)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/ae/Stability.png", text: " 3 Stability (3s): Cannot be knocked down, pushed back, pulled, launched, stunned, dazed, floated, sunk, feared, or taunted.", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f9/Attribute_bonus.png", text: "  Tethered Ally Healing per Target: 514 (0.1)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/9/97/Stun.png", text: "  Stun: 10.5½ seconds", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/8/8b/Duration.png", text: "  Duration Increase per Target: 1 second", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/1/1a/Combo.png", text: "  Combo Finisher: Blast", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/e/e2/Evade.png", text: "  Defiance Break: 150", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 240", type: "NoData" }] },
    { id: 42008, profession: "Guardian", name: "Chapter 4: Shining River", chat_link: "[&BhikAAA=]", description: "Tome. Release a torrent of pages describing the water cycle of the Elon River. Heal allies and grant them swiftness.", icon: "https://wiki.guildwars2.com/images/1/16/Chapter_4-_Shining_River.png", slot: "4", bundle: "Tome of Resolve", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "10" }, { icon: "https://wiki.guildwars2.com/images/f/f3/Healing.png", text: "  Healing: 326 (0.23)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f3/Healing.png", text: "  Healing: 287 (0.1)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/af/Swiftness.png", text: "  Swiftness (4s): +33% Movement Speed", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Pulses: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 360", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/1/1a/Combo.png", text: "  Combo Field: Water", type: "NoData" }] },
    { id: 62951, profession: "Warrior", name: "Dragon Slash—Reach", chat_link: "[&Buf1AAA=]", description: "Burst. Slash to create a blade of air that strikes foes in a line in front of you, ending Dragon Trigger. This attack consumes all charges to deal more damage.", icon: "https://wiki.guildwars2.com/images/e/eb/Dragon_Slash%E2%80%94Reach.png", slot: "3", bundle: "Dragon Trigger", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "1" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Minimum Damage: 206 (0.58)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Minimum Damage: 133 (0.375)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Maximum Damage: 3,627 (10.21)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Maximum Damage: 322 (0.9075)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/ae/Pierces.png", text: "  Pierces", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/0/09/Explosion.png", text: "  Explosion", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6e/Unblockable.png", text: "  Unblockable", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 900", type: "NoData" }] },
    { id: 63160, profession: "Thief", name: "Eternal Night", chat_link: "[&Brj2AAA=]", description: "Shroud. Strike at foes in front of you with your shadow magic, inflicting conditions. You and your tethered ally gain health for each enemy struck.", icon: "https://wiki.guildwars2.com/images/7/7b/Eternal_Night.png", slot: "4", bundle: "Enter Shadow Shroud", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "8" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage (2x): 1,436 (3.5)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/6/6a/Damage.png", text: "  Damage (2x): 820 (2.0)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a6/Chilled.png", text: "  Initial Strike (2s): -66% Skill Recharge Rate, -66% Movement Speed", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f9/Weakness.png", text: "  Second Strike (4s): -50% Endurance Regeneration, +50% Fumble (Unrestricted)", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/1/11/Poisoned.png", text: " 2 Poison per Strike (6s): 402 Damage, -33% Heal Effectiveness", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f9/Attribute_bonus.png", text: "  Tethered Ally Healing per Target: 514 (0.1)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f9/Attribute_bonus.png", text: "  Self-Heal: 514 (0.1)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/c/c5/Range.png", text: "  Range: 130", type: "NoData" }] },
    { id: 40679, profession: "Guardian", name: "Chapter 2: Radiant Recovery", chat_link: "[&BueeAAA=]", description: "Tome. Release magic from pages detailing the rebuilding of Vabbi, cleansing conditions on nearby allies. Allies are healed for each condition removed.", icon: "https://wiki.guildwars2.com/images/9/95/Chapter_2-_Radiant_Recovery.png", slot: "2", bundle: "Tome of Resolve", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "4" }, { icon: "https://wiki.guildwars2.com/images/f/f3/Healing.png", text: "  Per Removed Condition: 457 (0.77)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/f/f3/Healing.png", text: "  Per Removed Condition: 388 (0.5)?", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Conditions Removed: 3", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/2/28/Miscellaneous_effect.png", text: "  Conditions Removed: 1", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/5/53/Number_of_targets.png", text: "  Number of Allied Targets: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/a/a4/Radius.png", text: "  Radius: 240", type: "NoData" }] },
    { id: 42259, profession: "Guardian", name: "Tome of Courage", chat_link: "[&BhOlAAA=]", description: "Virtue:  Gain aegis periodically.Activate:  Conjure a mystic tome containing stories about the heroes of Istan.Each tome skill use consumes a page.", icon: "https://wiki.guildwars2.com/images/5/54/Tome_of_Courage.png", slot: "F3", bundle: "Profession mechanic", facts: [{ icon: "https://wiki.guildwars2.com/images/f/f4/Tango-recharge-darker.png", text: "Recharge", type: "Recharge", value: "75" }, { icon: "https://wiki.guildwars2.com/images/e/e5/Aegis.png", text: "  Aegis (Passive): Block the next incoming attack.", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/9/9d/Maximum_Count.png", text: "  Pages: 5", type: "NoData" }, { icon: "https://wiki.guildwars2.com/images/8/8b/Duration.png", text: "  Time to Trigger Passive: 40 seconds", type: "NoData" }] },
  ]